name       : concurrent-ruby
version    : 1.1.4
release    : 4
source     :
    - https://rubygems.org/downloads/concurrent-ruby-1.1.4.gem : e12e6ab140d8d99c14763a605b9671a5e182d4bf6dc951d4cb5debe86eeaacc7
license    : MIT
component  : programming.ruby
summary    : RubyGem - concurrent-ruby
description: |
    Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more. Inspired by Erlang, Clojure, Go, JavaScript, actors, and classic concurrency patterns.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
