name       : concurrent-ruby
version    : 1.0.5
release    : 1
source     :
    - https://rubygems.org/downloads/concurrent-ruby-1.0.5.gem : 8ee1206d0145a51f9ebdf735e4b5d6a957e085323b9db32e9b04f557dcd774a0
license    : MIT
component  : programming.ruby
summary    : RubyGem - concurrent-ruby
description: |
    Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more. Inspired by Erlang, Clojure, Go, JavaScript, actors, and classic concurrency patterns.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    %gem_install
